const navItems = [
  {main: "logo",
  content: <img src="https://img.icons8.com/metro/26/000000/mac-os.png"/>,
  subItems: []},
  {main: "Mac",
  content: "Mac",
  subItems: [
    {id: "MacBook", img:, new: false},
    {id: "MacBook Air", img:, new: false},
    {id: "MacBook Pro", img:, new: true},
    {id: "iMac", img:, new: true},
    {id: "iMac Pro", img:, new: false},
    {id: "Mac Pro", img:, new: true},
    {id: "Mac mini", img:, new: false},
    {id: "Compare", img:, new: false},
    {id: "Pro Display XDR", img:, new: true},
    {id: "Accessories", img:, new: false},
    {id: "Mojave", img:, new: false}
  ]},
  {main: "iPad",
  content: "iPad",
  subItems: [
    {id: "iPad Pro", img:, new: false},
    {id: "iPad Air", img:, new: true},
    {id: "iPad", img:, new: false},
    {id: "iPad mini", img:, new: true},
    {id: "Compare", img:, new: false},
    {id: "Apple Pencil", img:, new: false},
    {id: "Smart Keyboard", img:, new: false},
    {id: "Accessories", img:, new: false},
    {id: "iOS 12", img:, new: false}
  ]},
  {main: "iPhone",
  content: "iPhone",
  subItems: [
    {id: "iPhone Xs", img:, new: true},
    {id: "iPhone Xr", img:, new: true},
    {id: "iPhone 8", img:, new: false},
    {id: "iPhone 7", img:, new: false},
    {id: "Compare", img:, new: false},
    {id: "Apple Card", img:, new: false},
    {id: "AirPods", img:, new: false},
    {id: "Accessories", img:, new: false},
    {id: "iOS 12", img:, new: false}
  ]},
  {main: "Watch",
  content: "Watch",
  subItems: [
    {id: "Apple Watch Series 4", img:, new: false},
    {id: "Apple Watch Nike+", img:, new: false},
    {id: "Apple Watch Hermes", img:, new: false},
    {id: "Apple Watch Series 3", img:, new: false},
    {id: "watchOS", img:, new: false},
    {id: "Bands", img:, new: false},
    {id: "Accessories", img:, new: false},
    {id: "Compare", img:, new: false}
  ]},
  {main: "TV",
  content: "TV",
  subItems: [
    {id: "Apple TV app", img:, new: true},
    {id: "Apple TV+", img:, new: true},
    {id: "Apple TV 4K", img:, new: false},
    {id: "Apple TV HD", img:, new: false},
    {id: "AirPlay", img:, new: false},
    {id: "Accessories", img:, new: false}
  ]},
  {main: "Music",
  content: "Music",
  subItems: [
    {id: "Apple Music", img:, new: false},
    {id: "iTunes", img:, new: false},
    {id: "HomePod", img:, new: false},
    {id: "AirPods", img:, new: false},
    {id: "iPod touch", img:, new: true},
    {id: "Music Accessories", img:, new: false},
    {id: "Gift Cards", img:, new: false}
  ]},
  {main: "Support",
  content: "Support",
  subItems: []},
  {main: "Search",
  content: <img src="https://img.icons8.com/ios-glyphs/50/000000/search.png"/>,
  subItems: []},
  {main: "Bag",
  content: <img src="https://img.icons8.com/ios/50/000000/shopping-bag.png"/>,
  subItems: []},
]
